# Project Auto Created Config
spring:
  application:
    name: Blogifi

  profiles:
    active: prod

# For Showing Message #Where - For Showing Additional Message after new ResponseStatusException(HttpStatus.NOT_FOUND,"User With " +id+ "Not Found"))
server:
  port: 8080
  error:
    include-message: always
